### ISSUE TITLE
Add linux-headers to installation

### ISSUE THREAD

**Issue by k-amin07** [Unim8trix/G14Arch#1]
Hi, first of all, thank you for this guide. I was successfully able to install arch on my g14 with this, with the only difference being that I am using KDE instead of XFCE and using the linux-g14 kernel. The guide does not mention installation of linux-headers (or linux-g14-headers for me), without which trying to use the dGPU always results in black screen, at least with SDDM. Please add the following points to the guide:

- Install linux headers at some point: `sudo pacman -S linux-headers`
- Install nvidia packages: `sudo pacman -S nvidia-dkms nvidia-settings nvidia-prime`
- Can also optionally install bbswitch from AUR: `sudo pamac install bbswitch-g14-dkms-git`
- Install Optimus Manager from AUR: `sudo pamac install optimus-manager-qt` to be able to switch GPU. (requires restarting X, or logout and relogin)

**Comment by Unim8trix** [comment]
Hi and many Thanks! I will test your Infos and add it to the readme. Thanks for Sharing!
