### ISSUE TITLE
Restoring from stable snapshot

### ISSUE THREAD

**Issue by LarkyAngel** [Unim8trix/G14Arch#2]
Hi! Thank you for your guide! It helped me a lot during arch installation on my G14. As my Linux experience is average and I’m still learning, I don't really know how to restore system from stable snapshot. Please can you help me with this?

**Comment by Unim8trix** [comment]
Hi and Thanks!
Thats quite simple: on boot choose the stable bootentry and after boot, move this booted snapshot back.

A more easy way with more options is [Timeshift](https://github.com/teejee2008/timeshift) 
Its also in AUR, so you can install it verry easy..Try it
