### ISSUE TITLE
BackFlap Animation?

### ISSUE THREAD

**Issue by arshpreetsingh** [Unim8trix/G14Arch#3]
Hi Thanks for Nice notes, Just got my G14 some days back, I love this machine and Linux on this machine is Love in the heaven. 

Just wanted to know Are you able to run Backlight LED Animations in linux?

**Comment by Unim8trix** [comment]
Hi and many Thanks!

I havnt tried it, but if yourself give it a try it would be nice to have feedback:
https://asus-linux.org/asusctl/#config-options-anime
