### ISSUE TITLE
Battery life

### ISSUE THREAD

**Issue by JohnnyBoomKek** [Unim8trix/G14Arch#4]
First of all thanks a lot for the extensive readme. Will certainly be helpful. 

I'm considering to buy one of those. 

Can you share your experiences with the battery life using Arch? 
How does it compare to using windows with it's power management (as well as ROG's proprietary software)?

**Comment by Unim8trix** [comment]
Hi and Thank you! I cannot share differences to windows, cause i run arch only. Also iam using it on battery only a few hours, most of the time iam plugged in. I used the tweaks only for noise reasons.

Maybe you can find some infos on the [G14 Reddit](https://www.reddit.com/r/ZephyrusG14/)
